### PR TITLE
Add `promise` use overloads

### PR DESCRIPTION
**Pull request by blakeembrey**
Closes https://github.com/ForbesLindesay/throat/issues/28

### CODE REVIEW

**Comment by ForbesLindesay** [comment]
All those functions have the same type signature, can you add a test case to demonstrate that this actually works with typescript.

**Comment by blakeembrey** [comment]
Sorry for the delay. Took another pass to remove the duplication (using interfaces) and supporting promises, plus added a test. Let me know if I should add more tests, but it's using the same declaration now.

**Comment by velveteer** [comment]
Any movement on this?

**Comment by ForbesLindesay** [comment]
I think most people should be using a global Promise constructor by now. I left support for providing a custom one in the code, but I don't think it's needed in the type definitions. You can always just do `const throat: any = require('throat')` if you really need it.

**Pull request closed without merging**
